language: java

script: gradle test

notifications: # set notification options
  email:
    recipients:
      -1547272811@qq.com

    # change is when the repo status
    on_success: change
    on_failure: always
